export const genresList: GenresList[] = [
  { name: "News" },
  { name: "Sport" },
  { name: "Religion" },
  { name: "Weather" },
  { name: "Blues" },
  { name: "Classical" },
  { name: "Country" },
  { name: "Dance" },
  { name: "Disco" },
  { name: "Electronic" },
  { name: "Folk" },
  { name: "Funk" },
  { name: "Indie" },
  { name: "J-Pop" },
  { name: "Jazz" },
  { name: "K-Pop" },
  { name: "Latin" },
  { name: "Pop" },
  { name: "R&B" },
  { name: "Rap" },
  { name: "Rave" },
  { name: "Reggae" },
  { name: "Rock" },
  { name: "Ska" },
  { name: "Soul" },
];
